import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { createRcCoordinator } from './rc-coordinator-factory.js';
import type { RcCoordinator } from '../graph/rc-coordinator.js';
import type { GateResume } from '../../../core/graph/types.js';
import { getOrchestrator } from './shared-loaders.js';

let _coordinator: RcCoordinator | null = null;
function getCoordinator(): RcCoordinator {
  if (!_coordinator) _coordinator = createRcCoordinator(getOrchestrator());
  return _coordinator;
}

/**
 * Resume the RC graph coordinator to advance past the current gate.
 * The coordinator tracks gate lifecycle and provides crash recovery.
 */
async function resumeRcCoordinator(projectPath: string, gateResume: GateResume): Promise<void> {
  try {
    const coordinator = getCoordinator();
    const interrupt = coordinator.loadPendingInterrupt(projectPath);
    if (interrupt) {
      await coordinator.resume(projectPath, gateResume);
    }
  } catch (err) {
    console.error(`[rc_gate] Coordinator resume failed: ${(err as Error).message}`);
  }
}

export function registerRcGateTools(server: McpServer): void {
  // rc_gate - Process a gate decision
  server.registerTool(
    'rc_gate',
    {
      description:
        '[Starter+] Submit user\'s checkpoint decision for the current RC Method step. NEVER call without first presenting the step output to the user and getting their explicit approval. Valid decisions: "approve" advances to next step, "reject" stays at current step (include reason in feedback), "question" pauses for clarification. Checkpoints exist after all 8 steps. Step 6 (Build) checkpoint fires after all tasks are complete. After approve: the next step tool becomes available. After reject: re-run the current step tool with adjusted inputs.',
      inputSchema: {
        project_path: z.string().describe('Absolute path to the project directory'),
        decision: z.string().describe("Checkpoint decision: 'approve', 'reject [reason]', or 'question [text]'"),
        feedback: z.string().optional().describe('Optional additional feedback or reason for the decision'),
      },
      annotations: {
        title: 'RC Checkpoint Decision',
        readOnlyHint: false,
        destructiveHint: true,
        idempotentHint: false,
        openWorldHint: false,
      },
    },
    async ({ project_path, decision, feedback }) => {
      try {
        // Process gate decision via orchestrator (advances phase, saves state)
        const result = await getOrchestrator().gate(project_path, decision, feedback);

        // Resume the graph coordinator to advance past the gate node.
        // The next phase handler will return state unchanged (no _pendingInput),
        // so the graph stops at the next gate without doing extra work.
        const normalizedDecision = decision.toLowerCase().trim();
        const graphDecision: GateResume['decision'] = normalizedDecision.startsWith('approve') ? 'approve' : 'reject';
        await resumeRcCoordinator(project_path, { decision: graphDecision, feedback });

        return { content: [{ type: 'text' as const, text: result.text }] };
      } catch (err) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  // rc_save - Save an artifact generated by the host IDE
  server.registerTool(
    'rc_save',
    {
      description:
        '[Starter+] MANUAL MODE ONLY. Save an artifact generated by the host IDE (not by RC Engine tools) into the RC Method file structure. Use when the IDE\'s own AI generated a PRD, UX PRD, or task list that should be tracked by RC Method. Types: "prd" saves to rc-method/prds/, "prd-ux" saves UX child PRD, "tasks" saves task list. Do NOT use this for artifacts already saved by rc_define, rc_sequence, or ux_generate — those tools save automatically.',
      inputSchema: {
        project_path: z.string().describe('Absolute path to the project directory'),
        artifact_type: z
          .enum(['prd', 'prd-ux', 'tasks'])
          .describe("Type of artifact: 'prd' for main PRD, 'prd-ux' for UX child PRD, 'tasks' for task list"),
        content: z.string().describe('The full content of the artifact to save'),
      },
      annotations: {
        title: 'Save Artifact',
        readOnlyHint: false,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async ({ project_path, artifact_type, content }) => {
      try {
        const result = getOrchestrator().saveArtifact(project_path, artifact_type, content);
        return { content: [{ type: 'text' as const, text: result.text }] };
      } catch (err) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  // rc_reset - Clear project state for a fresh start
  server.registerTool(
    'rc_reset',
    {
      description:
        'Reset RC Method state for a project. Deletes the checkpoint from SQLite and the RC-STATE.md file, allowing rc_start to create a fresh project. Use when: (1) state is corrupted or stuck, (2) user wants to start over, (3) previous run left stale state. WARNING: This does NOT delete generated artifacts (PRDs, tasks, forge files) — only the pipeline state tracking. After reset: call rc_start to begin a new project.',
      inputSchema: {
        project_path: z.string().describe('Absolute path to the project directory'),
      },
    },
    async ({ project_path }) => {
      try {
        const result = getOrchestrator().reset(project_path);
        return { content: [{ type: 'text' as const, text: result.text }] };
      } catch (err) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  // rc_status - Get project status
  server.registerTool(
    'rc_status',
    {
      description:
        'Check RC Method progress. Read-only, safe to call anytime. Returns: current phase (1-8), gate statuses (approved/pending/rejected), saved artifacts list, and UX score if scored. Use this to orient yourself when resuming a session, when the user asks "where are we?", or before deciding which rc_ tool to call next. Also useful to verify a gate was recorded after calling rc_gate.',
      inputSchema: {
        project_path: z.string().describe('Absolute path to the project directory'),
      },
      annotations: {
        title: 'RC Status',
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    },
    async ({ project_path }) => {
      try {
        const result = getOrchestrator().status(project_path);
        return { content: [{ type: 'text' as const, text: result.text }] };
      } catch (err) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }],
          isError: true,
        };
      }
    },
  );
}
