import type { z } from 'zod';
import { Severity } from '../types.js';
import type { ScanResult, Finding, PostRCReportInputSchema } from '../types.js';
import { loadState } from '../state/state-manager.js';
import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';

type ReportInput = z.infer<typeof PostRCReportInputSchema>;

export async function postrcReport(args: ReportInput): Promise<string> {
  const { project_path, scan_id } = args;
  const state = await loadState(project_path);

  if (!state.projectPath) {
    return `No Post-RC configuration found. Run postrc_configure first.`;
  }

  const scan = scan_id ? state.scans.find((s) => s.id === scan_id) : state.lastScan;

  if (!scan) {
    return `No scan results found${scan_id ? ` for ID "${scan_id}"` : ''}. Run postrc_scan first.`;
  }

  // Generate markdown report
  const report = generateReport(state.projectName, scan, state.overrides.filter((o) => o.status === 'active').length);

  // Save report artifact
  const reportsDir = join(project_path, 'post-rc', 'reports');
  await mkdir(reportsDir, { recursive: true });
  const reportPath = join(reportsDir, `REPORT-${scan.id}.md`);
  await writeFile(reportPath, report, 'utf-8');

  return `## Post-RC Validation Report Generated

**Saved to:** post-rc/reports/REPORT-${scan.id}.md

${report}`;
}

function generateReport(projectName: string, scan: ScanResult, activeOverrides: number): string {
  const criticals = scan.findings.filter((f) => f.severity === Severity.Critical);
  const highs = scan.findings.filter((f) => f.severity === Severity.High);
  const mediums = scan.findings.filter((f) => f.severity === Severity.Medium);
  const lows = scan.findings.filter((f) => f.severity === Severity.Low);

  let report = `# Post-RC Validation Report: ${projectName}
## Generated: ${new Date().toISOString()}

**Scan ID:** ${scan.id}
**Duration:** ${scan.duration_ms}ms
**Gate Decision:** ${scan.gateDecision.toUpperCase()}
**Modules:** ${scan.modules.join(', ')}

---

## Summary

| Severity | Count |
|----------|-------|
| Critical | ${scan.summary.critical} |
| High | ${scan.summary.high} |
| Medium | ${scan.summary.medium} |
| Low | ${scan.summary.low} |
| **Total** | **${scan.summary.totalFindings}** |
| Overridden | ${activeOverrides} |

## Module Results

`;

  for (const mod of scan.summary.moduleSummaries) {
    report += `### ${mod.module.charAt(0).toUpperCase() + mod.module.slice(1)}\n`;
    report += `- **Status:** ${mod.passed ? 'PASSED' : 'FINDINGS DETECTED'}\n`;
    report += `- **Details:** ${mod.details}\n\n`;
  }

  if (criticals.length > 0) {
    report += `## Critical Findings (Must Fix)\n\n`;
    for (const f of criticals) {
      report += formatFinding(f);
    }
  }

  if (highs.length > 0) {
    report += `## High Findings (Should Fix)\n\n`;
    for (const f of highs) {
      report += formatFinding(f);
    }
  }

  if (mediums.length > 0) {
    report += `## Medium Findings\n\n`;
    for (const f of mediums) {
      report += formatFinding(f);
    }
  }

  if (lows.length > 0) {
    report += `## Low Findings\n\n`;
    for (const f of lows) {
      report += formatFinding(f);
    }
  }

  if (scan.findings.length === 0) {
    report += `## No Findings\n\nNo blocking findings detected by automated scanning.\n`;
  }

  // Check if legal findings are present
  const hasLegalFindings = scan.findings.some((f) => f.module === 'legal-claims' || f.module === 'legal-product');

  report += `\n---\n\n## Disclaimers\n\n`;
  report += `This report is generated by automated static pattern analysis and AI heuristic scanning. `;
  report += `It is provided as a **decision-support tool** and does not constitute a certification, audit, `;
  report += `or guarantee of software quality, security, or compliance.\n\n`;

  report += `**Scan coverage limitations:** This scanner checks for common vulnerability patterns and `;
  report += `compliance gaps. It cannot detect all possible security vulnerabilities, legal issues, or `;
  report += `regulatory non-compliance. No automated scan tool provides exhaustive coverage. `;
  report += `A "PASS" checkpoint decision means no blocking patterns were detected -- it is not a guarantee `;
  report += `of production readiness.\n\n`;

  if (hasLegalFindings) {
    report += `**Legal findings:** Legal and regulatory findings are automated compliance checks, not `;
    report += `legal counsel. Toerana is not a law firm and does not provide legal services. `;
    report += `Regulatory checks (HIPAA, PCI-DSS, COPPA, GDPR, FERPA, etc.) identify potential gaps `;
    report += `but do not certify compliance. Consult a qualified attorney for legal advice specific `;
    report += `to your product and jurisdiction.\n\n`;
  }

  report += `**Security findings:** Security scanning does not replace professional penetration `;
  report += `testing, SAST/DAST tools, or security audits. Toerana is not responsible for `;
  report += `vulnerabilities not detected by the scanner.\n\n`;

  report += `**AI-generated content:** Scan analysis includes AI-generated assessments that may `;
  report += `contain errors or omissions. All findings should be reviewed by qualified professionals `;
  report += `before acting on them.\n\n`;

  report += `**Liability:** This report and the Post-RC Method tools are provided "as is" without `;
  report += `warranty of any kind. Toerana accepts no liability for decisions made, actions taken, `;
  report += `or outcomes resulting from the use of this report. Users assume full responsibility for `;
  report += `validating findings and for any reliance placed upon them.\n\n`;

  report += `---\n\n*Generated by Post-RC Method Agent v1.0.0 -- (c) ${new Date().getFullYear()} Toerana*\n`;
  return report;
}

function formatFinding(f: Finding): string {
  let out = `### ${f.id}: ${f.title}\n`;
  out += `- **Module:** ${f.module}\n`;
  out += `- **Severity:** ${f.severity.toUpperCase()}\n`;
  if (f.cweId) out += `- **CWE:** ${f.cweId}\n`;
  if (f.filePath) out += `- **File:** ${f.filePath}\n`;
  out += `- **Description:** ${f.description}\n`;
  out += `- **Remediation:** ${f.remediation}\n\n`;
  return out;
}
