/**
 * Playbook / Architecture Decision Record (ARD) Generator.
 *
 * Aggregates all RC Engine pipeline outputs into a single comprehensive
 * document. This is the "master deliverable" that a non-technical user
 * can hand to a development team or use as their project playbook.
 *
 * Sections:
 *   1. Executive Summary
 *   2. Research Findings (from Pre-RC)
 *   3. Product Requirements (from PRD)
 *   4. Design Decisions (from Design step)
 *   5. Architecture Decisions (from Architect phase)
 *   6. Implementation Plan (from Sequence phase)
 *   7. Quality & Security (from Post-RC)
 *   8. Traceability Matrix (from Traceability)
 *   9. Cost & Value Summary (from Value Calculator)
 *  10. Appendix: Full Artifact Index
 */

import fs from 'node:fs';
import path from 'node:path';

export interface PlaybookInput {
  projectPath: string;
  projectName: string;
}

export interface PlaybookResult {
  markdown: string;
  savedPath: string;
}

/**
 * Generate the playbook by reading all available artifacts from the project directory.
 */
export function generatePlaybook(input: PlaybookInput): PlaybookResult {
  const { projectPath, projectName } = input;
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const sections: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  sections.push(`# ${projectName} -- Project Playbook

> Generated by RC Engine on ${dateStr}
> This document is your complete project playbook. It contains every decision,
> requirement, and plan produced during the RC Engine pipeline.

---
`);

  // ── 1. Executive Summary ────────────────────────────────────────────────
  sections.push(`## 1. Executive Summary

This playbook documents the complete product development process for **${projectName}**,
covering research, requirements, design, architecture, implementation planning,
and quality validation.
`);

  // ── 2. Research Findings ────────────────────────────────────────────────
  const researchContent = collectFiles(projectPath, 'pre-rc-research', ['.md']);
  if (researchContent.length > 0) {
    sections.push(`## 2. Research Findings

The following research was conducted by specialized AI analysts:
`);
    for (const { filename, content } of researchContent) {
      // Include a summary (first 80 lines) of each research file
      const summary = content.split('\n').slice(0, 80).join('\n');
      const isTruncated = content.split('\n').length > 80;
      sections.push(
        `### ${cleanFilename(filename)}\n\n${summary}${isTruncated ? '\n\n*[Truncated -- see full file in pre-rc-research/]*' : ''}\n`,
      );
    }
  } else {
    sections.push(`## 2. Research Findings\n\n*No Pre-RC research was conducted for this project.*\n`);
  }

  // ── 3. Product Requirements ─────────────────────────────────────────────
  const prdContent = collectFiles(projectPath, 'rc-method/prds', ['.md']);
  if (prdContent.length > 0) {
    sections.push(`## 3. Product Requirements\n`);
    for (const { filename, content } of prdContent) {
      sections.push(`### ${cleanFilename(filename)}\n\n${content}\n`);
    }
  } else {
    sections.push(`## 3. Product Requirements\n\n*No PRD was generated.*\n`);
  }

  // ── 4. Design Decisions ─────────────────────────────────────────────────
  const designSpec = readJsonSafe(projectPath, 'rc-method/design');
  if (designSpec) {
    sections.push(`## 4. Design Decisions\n`);
    try {
      const spec = JSON.parse(designSpec);
      sections.push(`**ICP Summary:** ${spec.icpSummary ?? 'N/A'}\n`);

      if (spec.options) {
        for (const opt of spec.options) {
          sections.push(`### Option ${opt.id}: ${opt.name}

- **Personality:** ${opt.style?.personality ?? 'N/A'}
- **ICP Alignment:** ${opt.icpAlignment ?? 'N/A'}%
- **Colors:** ${opt.style?.colorPalette?.primary ?? ''} / ${opt.style?.colorPalette?.secondary ?? ''}
- **Typography:** ${opt.style?.typography?.headingFont ?? ''} + ${opt.style?.typography?.bodyFont ?? ''}

**Strengths:** ${(opt.tradeoffs?.strengths ?? []).join(', ')}

**Tradeoffs:** ${(opt.tradeoffs?.weaknesses ?? []).join(', ')}
`);
        }
      }

      if (spec.recommendation) {
        sections.push(`### Recommended: Option ${spec.recommendation.optionId}
${spec.recommendation.reason}
`);
      }
    } catch {
      sections.push(`*Design spec found but could not be parsed.*\n`);
    }
  } else {
    sections.push(`## 4. Design Decisions\n\n*No design generation was performed.*\n`);
  }

  // ── 5. Architecture Decisions ───────────────────────────────────────────
  const archContent = collectFiles(projectPath, 'rc-method/artifacts', ['.md']);
  if (archContent.length > 0) {
    sections.push(`## 5. Architecture Decisions\n`);
    for (const { filename, content } of archContent) {
      sections.push(`### ${cleanFilename(filename)}\n\n${content}\n`);
    }
  } else {
    sections.push(`## 5. Architecture Decisions\n\n*Architecture phase was not completed.*\n`);
  }

  // ── 6. Implementation Plan ──────────────────────────────────────────────
  const taskContent = collectFiles(projectPath, 'rc-method/tasks', ['.md']);
  if (taskContent.length > 0) {
    sections.push(`## 6. Implementation Plan\n`);
    for (const { filename, content } of taskContent) {
      sections.push(`### ${cleanFilename(filename)}\n\n${content}\n`);
    }
  } else {
    sections.push(`## 6. Implementation Plan\n\n*Task sequence was not generated.*\n`);
  }

  // ── 7. Quality & Security ──────────────────────────────────────────────
  const secContent = collectFiles(projectPath, 'post-rc', ['.md', '.json']);
  if (secContent.length > 0) {
    sections.push(`## 7. Quality & Security\n`);
    for (const { filename, content } of secContent) {
      if (filename.endsWith('.json')) {
        try {
          const parsed = JSON.parse(content);
          sections.push(
            `### ${cleanFilename(filename)}\n\n\`\`\`json\n${JSON.stringify(parsed, null, 2).slice(0, 3000)}\n\`\`\`\n`,
          );
        } catch {
          sections.push(`### ${cleanFilename(filename)}\n\n*Could not parse JSON.*\n`);
        }
      } else {
        sections.push(`### ${cleanFilename(filename)}\n\n${content}\n`);
      }
    }
  } else {
    sections.push(`## 7. Quality & Security\n\n*Post-RC validation was not performed.*\n`);
  }

  // ── 8. Traceability Matrix ─────────────────────────────────────────────
  const traceContent = collectFiles(projectPath, 'rc-traceability', ['.md', '.json']);
  if (traceContent.length > 0) {
    sections.push(`## 8. Traceability Matrix\n`);
    for (const { filename, content } of traceContent) {
      const summary = content.split('\n').slice(0, 60).join('\n');
      sections.push(`### ${cleanFilename(filename)}\n\n${summary}\n`);
    }
  } else {
    sections.push(`## 8. Traceability Matrix\n\n*Traceability was not configured.*\n`);
  }

  // ── 9. Cost & Value Summary ────────────────────────────────────────────
  sections.push(`## 9. Cost & Value Summary

*See the Value Report in the web UI for a detailed breakdown of human-equivalent
cost savings, speed multiplier, and team equivalence.*
`);

  // ── 10. Appendix: Artifact Index ───────────────────────────────────────
  const allFiles = listAllArtifacts(projectPath);
  if (allFiles.length > 0) {
    sections.push(`## 10. Appendix: Artifact Index\n`);
    sections.push(`| File | Directory | Size |`);
    sections.push(`|------|-----------|------|`);
    for (const f of allFiles) {
      sections.push(`| ${f.name} | ${f.dir} | ${formatSize(f.size)} |`);
    }
    sections.push('');
  }

  // ── Save ────────────────────────────────────────────────────────────────
  const markdown = sections.join('\n');
  const outputDir = path.join(projectPath, 'rc-method');
  fs.mkdirSync(outputDir, { recursive: true });

  const outputPath = path.join(outputDir, `PLAYBOOK-${sanitize(projectName)}.md`);
  fs.writeFileSync(outputPath, markdown, 'utf-8');

  return {
    markdown,
    savedPath: `rc-method/PLAYBOOK-${sanitize(projectName)}.md`,
  };
}

// ── Helpers ─────────────────────────────────────────────────────────────

function collectFiles(
  projectPath: string,
  subDir: string,
  extensions: string[],
): Array<{ filename: string; content: string }> {
  const dir = path.join(projectPath, subDir);
  if (!fs.existsSync(dir)) return [];

  try {
    return fs
      .readdirSync(dir)
      .filter((f) => extensions.some((ext) => f.toLowerCase().endsWith(ext)))
      .filter((f) => !f.includes('STATE') && f !== 'config.json')
      .map((f) => ({
        filename: f,
        content: fs.readFileSync(path.join(dir, f), 'utf-8'),
      }));
  } catch {
    return [];
  }
}

function readJsonSafe(projectPath: string, subDir: string): string | null {
  const dir = path.join(projectPath, subDir);
  if (!fs.existsSync(dir)) return null;

  try {
    const jsonFiles = fs.readdirSync(dir).filter((f) => f.endsWith('.json'));
    if (jsonFiles.length === 0) return null;
    return fs.readFileSync(path.join(dir, jsonFiles[0]), 'utf-8');
  } catch {
    return null;
  }
}

function listAllArtifacts(projectPath: string): Array<{ name: string; dir: string; size: number }> {
  const results: Array<{ name: string; dir: string; size: number }> = [];
  const dirs = [
    'pre-rc-research',
    'rc-method/prds',
    'rc-method/tasks',
    'rc-method/design',
    'rc-method/forge',
    'post-rc',
    'rc-traceability',
  ];

  for (const dir of dirs) {
    const fullDir = path.join(projectPath, dir);
    if (!fs.existsSync(fullDir)) continue;
    try {
      for (const entry of fs.readdirSync(fullDir, { withFileTypes: true })) {
        if (!entry.isFile()) continue;
        const stat = fs.statSync(path.join(fullDir, entry.name));
        results.push({ name: entry.name, dir, size: stat.size });
      }
    } catch {
      // Skip
    }
  }

  return results;
}

function cleanFilename(filename: string): string {
  return filename
    .replace(/\.(md|json|html)$/i, '')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function sanitize(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
