import type { z } from 'zod';
import { writeFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join, basename } from 'path';
import { LLMEnhancePrdOutputSchema } from '../types.js';
import type { TraceabilityMatrix, Requirement, TraceSummary, TraceEnhancePrdInputSchema } from '../types.js';
import { parsePrd } from '../parsers/prd-parser.js';
import { assignIds } from '../id/id-generator.js';
import { ensureDirectories, saveTraceability, getEnhancedDir } from '../state/state-manager.js';
import { hasApiKey } from '../../../shared/config.js';
import { llmFactory } from '../../../shared/llm/factory.js';
import { LLMProvider } from '../../../shared/types.js';
import { tokenTracker } from '../../../shared/token-tracker.js';
import { audit } from '../../../shared/audit.js';
import { recordCost } from '../../../shared/cost-tracker.js';
import { recordModelPerformance } from '../../../shared/learning.js';

type EnhancePrdInput = z.infer<typeof TraceEnhancePrdInputSchema>;

// Glob-like discovery patterns for PRDs
const PRD_PATTERNS = ['pre-rc-research/prd-*.md', 'rc-method/prds/PRD-*-master.md'];

async function discoverPrd(projectPath: string): Promise<{ content: string; filename: string } | null> {
  // Try each pattern location
  const { readdir } = await import('fs/promises');

  // Pattern 1: Pre-RC research output
  const preRcDir = join(projectPath, 'pre-rc-research');
  if (existsSync(preRcDir)) {
    const files = await readdir(preRcDir);
    const prdFile = files.find((f) => f.startsWith('prd-') && f.endsWith('.md'));
    if (prdFile) {
      const { readFile } = await import('fs/promises');
      const content = await readFile(join(preRcDir, prdFile), 'utf-8');
      return { content, filename: prdFile };
    }
  }

  // Pattern 2: RC Method PRD
  const rcPrdDir = join(projectPath, 'rc-method', 'prds');
  if (existsSync(rcPrdDir)) {
    const files = await readdir(rcPrdDir);
    const masterPrd = files.find((f) => f.startsWith('PRD-') && f.includes('-master') && f.endsWith('.md'));
    if (masterPrd) {
      const { readFile } = await import('fs/promises');
      const content = await readFile(join(rcPrdDir, masterPrd), 'utf-8');
      return { content, filename: masterPrd };
    }
  }

  return null;
}

function buildPassthroughPrompt(prdContent: string): string {
  return `## RC Traceability Addon - PRD Enhancement Prompt

You are analyzing a PRD (Product Requirements Document) to extract requirements, assign stable IDs, and generate testable acceptance criteria.

### Instructions

1. Read the PRD below carefully.
2. Extract every requirement statement (functional, security, performance, UX, data, integration, observability, business rules).
3. For each requirement, assign a category:
   - FUNC (functional), SEC (security), PERF (performance), UX (UX/accessibility)
   - DATA (data model), INT (integration), OBS (observability), BIZ (business rules)
4. For each requirement, generate a testable acceptance criterion in Given/When/Then format.
5. Return a JSON object matching this schema:
   \`\`\`json
   {
     "requirements": [
       {
         "title": "Short requirement title",
         "description": "Full requirement description",
         "sourceSection": "PRD section heading this came from",
         "suggestedCategory": "FUNC|SEC|PERF|UX|DATA|INT|OBS|BIZ",
         "acceptanceCriteria": "Given [context], When [action], Then [expected result]"
       }
     ]
   }
   \`\`\`

### PRD Content

${prdContent}

### Output

Return ONLY the JSON object. No other text.`;
}

function generateEnhancedPrdMarkdown(originalContent: string, requirements: Requirement[]): string {
  let md = `# Enhanced PRD - Requirements Traceability\n\n`;
  md += `> Auto-generated by RC Traceability Addon\n`;
  md += `> Generated: ${new Date().toISOString()}\n`;
  md += `> Total requirements: ${requirements.length}\n\n`;
  md += `---\n\n`;

  // Group by category
  const groups = new Map<string, Requirement[]>();
  for (const req of requirements) {
    const group = groups.get(req.category) || [];
    group.push(req);
    groups.set(req.category, group);
  }

  // Category display names
  const categoryNames: Record<string, string> = {
    FUNC: 'Functional Requirements',
    SEC: 'Security Requirements',
    PERF: 'Performance Requirements',
    UX: 'UX/Accessibility Requirements',
    DATA: 'Data Model Requirements',
    INT: 'Integration Requirements',
    OBS: 'Observability Requirements',
    BIZ: 'Business Rules',
  };

  for (const [category, reqs] of groups) {
    md += `## ${categoryNames[category] || category}\n\n`;
    for (const req of reqs) {
      md += `### ${req.id}: ${req.title}\n\n`;
      md += `- **Description:** ${req.description}\n`;
      md += `- **Source:** ${req.sourceSection}\n`;
      md += `- **Status:** ${req.status}\n`;
      if (req.acceptanceCriteria) {
        md += `- **Acceptance Criteria:** ${req.acceptanceCriteria}\n`;
      }
      md += `\n`;
    }
  }

  md += `---\n\n`;
  md += `## Original PRD\n\n`;
  md += originalContent;

  return md;
}

export async function traceEnhancePrd(args: EnhancePrdInput): Promise<string> {
  const { project_path, prd_content } = args;

  await ensureDirectories(project_path);

  // Step 1: Get PRD content
  let content: string;
  let filename: string;

  if (prd_content) {
    content = prd_content;
    filename = 'provided-inline';
  } else {
    const discovered = await discoverPrd(project_path);
    if (!discovered) {
      return `ERROR: No PRD found at ${project_path}.\n\nLooked in:\n${PRD_PATTERNS.map((p) => `  - ${p}`).join('\n')}\n\nEither provide prd_content directly or place a PRD file in one of these locations.`;
    }
    content = discovered.content;
    filename = discovered.filename;
  }

  // Step 2: Parse PRD and extract requirements
  const parsedRequirements = parsePrd(content);

  if (parsedRequirements.length === 0) {
    return `WARNING: No requirements extracted from PRD (${filename}).\n\nThe parser looks for:\n- Checkbox items (acceptance criteria)\n- Bullet points with modal verbs (must, shall, should)\n- Sentences with requirement language\n\nCheck that your PRD contains clearly stated requirements.`;
  }

  // Step 3: Assign deterministic IDs
  const requirements = assignIds(parsedRequirements);

  // Step 4: Handle autonomous vs passthrough mode
  if (hasApiKey) {
    // Autonomous mode: Use shared LLM factory to generate acceptance criteria
    try {
      const client = llmFactory.getClient(LLMProvider.Claude);

      const prompt = buildPassthroughPrompt(content);
      const response = await client.chatWithRetry({
        messages: [{ role: 'user', content: prompt }],
        maxTokens: 4096,
      });

      tokenTracker.record('traceability', 'trace_enhance_prd', response.tokensUsed, response.provider, { inputTokens: response.inputTokens, outputTokens: response.outputTokens });
      recordCost({
        pipelineId: 'trace-session',
        domain: 'traceability',
        tool: 'trace_enhance_prd',
        provider: response.provider,
        model: client.getModel(),
        inputTokens: response.inputTokens ?? 0,
        outputTokens: response.outputTokens ?? response.tokensUsed,
      });
      recordModelPerformance({
        provider: response.provider,
        model: client.getModel(),
        taskType: 'trace-enhance-prd',
        tokensUsed: response.tokensUsed,
        success: true,
      });

      const responseText = response.content;

      // Extract JSON from response
      const jsonMatch = responseText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = LLMEnhancePrdOutputSchema.safeParse(JSON.parse(jsonMatch[0]));
        if (parsed.success) {
          // Merge LLM acceptance criteria into requirements
          for (const llmReq of parsed.data.requirements) {
            const match = requirements.find(
              (r) =>
                r.sourceSection === llmReq.sourceSection &&
                r.title.toLowerCase().includes(llmReq.title.toLowerCase().slice(0, 30)),
            );
            if (match) {
              match.acceptanceCriteria = llmReq.acceptanceCriteria;
            }
          }
        }
      }
    } catch (err) {
      // Fall back to passthrough if LLM call fails
      console.error(`[traceability] LLM call failed, using parsed requirements: ${(err as Error).message}`);
    }
  }

  // Step 5: Build and save traceability matrix
  const projectName = basename(project_path);
  const enhancedPrdFilename = `PRD-ENHANCED-${projectName}.md`;
  const enhancedPrdPath = join(getEnhancedDir(project_path), enhancedPrdFilename);

  const summary: TraceSummary = {
    totalRequirements: requirements.length,
    implemented: 0,
    verified: 0,
    failed: 0,
    orphanRequirements: requirements.map((r) => r.id),
    orphanTasks: [],
    coveragePercent: 0,
  };

  const matrix: TraceabilityMatrix = {
    projectName,
    enhancedPrdPath: `rc-traceability/enhanced/${enhancedPrdFilename}`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    requirements,
    summary,
  };

  await saveTraceability(project_path, matrix);
  audit('artifact.create', 'traceability', project_path, {
    type: 'requirement-matrix',
    requirementCount: requirements.length,
  });

  // Step 6: Save enhanced PRD markdown
  const enhancedPrdContent = generateEnhancedPrdMarkdown(content, requirements);
  await writeFile(enhancedPrdPath, enhancedPrdContent, 'utf-8');

  // Step 7: Build output
  const categoryBreakdown = new Map<string, number>();
  for (const req of requirements) {
    categoryBreakdown.set(req.category, (categoryBreakdown.get(req.category) || 0) + 1);
  }

  let output = `
===============================================
  RC TRACEABILITY ADDON: PRD ENHANCEMENT
===============================================

  Source PRD: ${filename}
  Mode: ${hasApiKey ? 'Automatic' : 'Manual'}

  REQUIREMENTS EXTRACTED: ${requirements.length}

  BREAKDOWN BY CATEGORY:
`;

  for (const [cat, count] of categoryBreakdown) {
    output += `    ${cat}: ${count}\n`;
  }

  output += `
  FILES CREATED:
    rc-traceability/TRACEABILITY.json
    rc-traceability/enhanced/${enhancedPrdFilename}

  COVERAGE BASELINE: 0% (all requirements unimplemented)
`;

  if (!hasApiKey) {
    output += `
  MANUAL MODE:
    Acceptance criteria were NOT generated (no API key).
    To generate Given/When/Then criteria:
    1. Set ANTHROPIC_API_KEY and re-run, OR
    2. Use the prompt below in your IDE:

${buildPassthroughPrompt(content).slice(0, 500)}...
    [Prompt truncated - full prompt available in enhanced PRD]
`;
  }

  output += `
  NEXT STEPS:
    -> Build your project using RC Method
    -> Run Post-RC scan
    -> Then use "trace_map_findings" to map results back
    -> Use "trace_status" to check coverage anytime
===============================================`;

  return output;
}
